project:
  type: website

website:
  title: "Neural ensembles and memory"
  navbar:
    left:
      - href: research
        text: Research
      - href: people
        text: People
      - href: publications
        text: Publications
      - href: outreach
        text: Outreach
      - href: contact
        text: Contact

format:
  html:
    theme:
      - litera