project:
  type: website

website:
  title: "EAM" 
  favicon: "LOGO_orange.png"
  navbar:
    logo: 'LOGO_orange.png'
    logo-alt: 'N'
    left:
      - href: research
        text: Research
      - href: people
        text: People
      - href: publications
        text: Publications
      - href: contact
        text: Contact
    #right:

format:
  html:
    theme: lux
    linkcolor: green