project:
  type: website

website:
  title: "Neural ensembles and memory"
  #favicon: "images/favicon/apple-touch-icon.png"
  navbar:
    # logo: 'UK-logo-square-EN.png'
    left:
      - href: research
        text: Research
      - href: people
        text: People
      - href: publications
        text: Publications
      - href: contact
        text: Contact
    #right:
    #  - text: ![](brain_center.png)

format:
  html:
    theme:
      - lux