project:
  type: website

website:
  title: "eural ensembles and memory" #
  favicon: "neam.svg"
  navbar:
    logo: 'neam.svg'
    logo-alt: 'N'
    left:
      - href: research
        text: Research
      - href: people
        text: People
      - href: publications
        text: Publications
      - href: contact
        text: Contact
    right:
      - icon: 'UK-logo-square-EN.png'

format:
  html:
    theme: lux
    linkcolor: maroon